export type CompanyCategory =
  | 'AI/ML Platform'
  | 'Data Infrastructure'
  | 'Security & Identity'
  | 'GTM & Revenue Tech'
  | 'Logistics & Supply Chain'
  | 'Automotive Software'
  | 'Workflow Automation'
  | 'Other'

export type FundingStage =
  | 'Series A'
  | 'Series B'
  | 'Series C'
  | 'Series D'
  | 'Series E'
  | 'Series F+'
  | 'Pre-IPO'
  | 'Public'
  | 'Private'

export interface Company {
  id: string
  name: string
  category: CompanyCategory
  fundingStage: FundingStage
  totalRaised?: string
  valuation?: string
  arrEstimate?: string
  growthRate?: string
  employees?: string
  hq?: string
  remoteOk: boolean
  careersUrl: string
  linkedinUrl?: string
  description: string
  icpScore: number
  icpBreakdown: ICPBreakdown
  targetRoles: string[]
  notes?: string
}

export interface ICPBreakdown {
  fundingStage: number      // max 20
  growthRate: number        // max 20
  activelyHiring: number    // max 20
  categoryMatch: number     // max 15
  remoteOk: number          // max 10
  fortune1000Buyers: number // max 10
  compSize: number          // max 5
}

// ICP Scoring Logic
export function calculateICPScore(breakdown: ICPBreakdown): number {
  return Object.values(breakdown).reduce((sum, val) => sum + val, 0)
}

export const TARGET_COMPANIES: Company[] = [
  // AI / ML PLATFORMS
  {
    id: 'glean',
    name: 'Glean',
    category: 'AI/ML Platform',
    fundingStage: 'Series F+',
    totalRaised: '$615M',
    valuation: '$7.2B',
    arrEstimate: '$100M+',
    growthRate: '450% YoY',
    employees: '850+',
    hq: 'Palo Alto, CA',
    remoteOk: true,
    careersUrl: 'https://www.glean.com/careers',
    linkedinUrl: 'https://www.linkedin.com/company/gleanwork',
    description: 'Enterprise AI search and knowledge management platform. Work AI for the Fortune 500.',
    icpScore: 95,
    icpBreakdown: { fundingStage: 18, growthRate: 20, activelyHiring: 20, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Top priority. Doubling sales team. Direct overlap with F1000 data/AI buyers.',
  },
  {
    id: 'anthropic',
    name: 'Anthropic / Claude AI',
    category: 'AI/ML Platform',
    fundingStage: 'Series F+',
    totalRaised: '$7B+',
    valuation: '$60B+',
    employees: '1000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.anthropic.com/careers',
    linkedinUrl: 'https://www.linkedin.com/company/anthropicresearch',
    description: 'AI safety company building Claude. Enterprise API and platform sales growing rapidly.',
    icpScore: 90,
    icpBreakdown: { fundingStage: 20, growthRate: 20, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 5, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'polyai',
    name: 'PolyAI',
    category: 'AI/ML Platform',
    fundingStage: 'Series C',
    totalRaised: '$116M',
    employees: '200+',
    hq: 'London / New York',
    remoteOk: true,
    careersUrl: 'https://poly.ai/careers',
    linkedinUrl: 'https://www.linkedin.com/company/poly-ai',
    description: 'Conversational AI for enterprise customer service. Voice AI at scale.',
    icpScore: 78,
    icpBreakdown: { fundingStage: 14, growthRate: 16, activelyHiring: 15, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 5, compSize: 3 },
    targetRoles: ['Enterprise Account Executive', 'Mid-Market AE'],
  },
  {
    id: 'eliseai',
    name: 'EliseAI',
    category: 'AI/ML Platform',
    fundingStage: 'Series D',
    totalRaised: '$75M',
    employees: '200+',
    hq: 'New York, NY',
    remoteOk: true,
    careersUrl: 'https://www.eliseai.com/careers',
    description: 'AI operating system for housing and healthcare industries.',
    icpScore: 74,
    icpBreakdown: { fundingStage: 15, growthRate: 15, activelyHiring: 14, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 5, compSize: 2 },
    targetRoles: ['Enterprise Account Executive'],
  },
  {
    id: 'cresta',
    name: 'Cresta',
    category: 'AI/ML Platform',
    fundingStage: 'Series C',
    totalRaised: '$151M',
    employees: '200+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://cresta.com/careers',
    description: 'Real-time AI coaching for contact centers. Enterprise revenue intelligence.',
    icpScore: 76,
    icpBreakdown: { fundingStage: 14, growthRate: 15, activelyHiring: 15, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 5, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'luminize',
    name: 'Luminize',
    category: 'AI/ML Platform',
    fundingStage: 'Series B',
    employees: '100+',
    hq: 'Austin, TX',
    remoteOk: true,
    careersUrl: 'https://luminize.ai/careers',
    description: 'AI-powered Amazon marketplace acceleration and analytics platform.',
    icpScore: 72,
    icpBreakdown: { fundingStage: 12, growthRate: 14, activelyHiring: 16, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 5, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Previously researched. Strong CPG/retail vertical overlap.',
  },

  // DATA INFRASTRUCTURE
  {
    id: 'databricks',
    name: 'Databricks',
    category: 'Data Infrastructure',
    fundingStage: 'Pre-IPO',
    totalRaised: '$4B+',
    valuation: '$62B',
    arrEstimate: '$1.6B+',
    growthRate: '50%+ YoY',
    employees: '6000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.databricks.com/company/careers',
    linkedinUrl: 'https://www.linkedin.com/company/databricks',
    description: 'Unified data analytics and AI platform. The data lakehouse for the enterprise.',
    icpScore: 93,
    icpBreakdown: { fundingStage: 18, growthRate: 18, activelyHiring: 20, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'A++ rated employer. Top priority for data infrastructure role.',
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'Data Infrastructure',
    fundingStage: 'Public',
    arrEstimate: '$3B+',
    growthRate: '30%+ YoY',
    employees: '7000+',
    hq: 'Bozeman, MT',
    remoteOk: true,
    careersUrl: 'https://careers.snowflake.com',
    linkedinUrl: 'https://www.linkedin.com/company/snowflake-computing',
    description: 'Cloud data platform. AI Data Cloud for the enterprise.',
    icpScore: 88,
    icpBreakdown: { fundingStage: 15, growthRate: 16, activelyHiring: 20, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'acceldata',
    name: 'Acceldata.io',
    category: 'Data Infrastructure',
    fundingStage: 'Series C',
    totalRaised: '$80M',
    employees: '300+',
    hq: 'San Jose, CA',
    remoteOk: true,
    careersUrl: 'https://www.acceldata.io/careers',
    description: 'Enterprise data observability platform. Data reliability for the modern stack.',
    icpScore: 73,
    icpBreakdown: { fundingStage: 14, growthRate: 14, activelyHiring: 14, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 5, compSize: 1 },
    targetRoles: ['Enterprise Account Executive'],
  },
  {
    id: 'fivetran',
    name: 'Fivetran',
    category: 'Data Infrastructure',
    fundingStage: 'Pre-IPO',
    totalRaised: '$730M',
    valuation: '$5.6B',
    employees: '1200+',
    hq: 'Oakland, CA',
    remoteOk: true,
    careersUrl: 'https://www.fivetran.com/careers',
    description: 'Automated data movement platform. ELT pipelines for the enterprise.',
    icpScore: 84,
    icpBreakdown: { fundingStage: 17, growthRate: 15, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 7, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    category: 'Data Infrastructure',
    fundingStage: 'Public',
    arrEstimate: '$300M+',
    employees: '700+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://amplitude.com/careers',
    description: 'Digital analytics platform. Product intelligence for enterprise.',
    icpScore: 80,
    icpBreakdown: { fundingStage: 14, growthRate: 14, activelyHiring: 18, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 8, compSize: 3 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'hightouch',
    name: 'Hightouch',
    category: 'Data Infrastructure',
    fundingStage: 'Series C',
    totalRaised: '$172M',
    arrEstimate: '$23M',
    employees: '264',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://hightouch.com/careers',
    description: 'Data activation and AI marketing platform. Reverse ETL and customer data sync.',
    icpScore: 76,
    icpBreakdown: { fundingStage: 14, growthRate: 16, activelyHiring: 14, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 5, compSize: 2 },
    targetRoles: ['Enterprise Account Executive'],
  },

  // SECURITY & IDENTITY
  {
    id: 'okta',
    name: 'Okta',
    category: 'Security & Identity',
    fundingStage: 'Public',
    arrEstimate: '$2.2B+',
    employees: '6000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.okta.com/company/careers',
    description: 'Identity and access management for the enterprise. Zero trust security.',
    icpScore: 85,
    icpBreakdown: { fundingStage: 14, growthRate: 14, activelyHiring: 20, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'crowdstrike',
    name: 'CrowdStrike',
    category: 'Security & Identity',
    fundingStage: 'Public',
    arrEstimate: '$3.7B+',
    growthRate: '33% YoY',
    employees: '8000+',
    hq: 'Austin, TX',
    remoteOk: true,
    careersUrl: 'https://www.crowdstrike.com/careers',
    description: 'Cloud-native endpoint and identity protection platform.',
    icpScore: 84,
    icpBreakdown: { fundingStage: 14, growthRate: 15, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'sentinelone',
    name: 'SentinelOne',
    category: 'Security & Identity',
    fundingStage: 'Public',
    arrEstimate: '$700M+',
    employees: '2500+',
    hq: 'Mountain View, CA',
    remoteOk: true,
    careersUrl: 'https://www.sentinelone.com/jobs',
    description: 'AI-powered cybersecurity platform. Autonomous threat detection and response.',
    icpScore: 82,
    icpBreakdown: { fundingStage: 14, growthRate: 15, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'vanta',
    name: 'Vanta',
    category: 'Security & Identity',
    fundingStage: 'Series C',
    totalRaised: '$203M',
    valuation: '$1.6B',
    employees: '500+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.vanta.com/careers',
    description: 'Automated security compliance platform. SOC 2, ISO 27001 for the enterprise.',
    icpScore: 79,
    icpBreakdown: { fundingStage: 14, growthRate: 16, activelyHiring: 16, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Mid-Market AE'],
  },
  {
    id: 'netskope',
    name: 'Netskope',
    category: 'Security & Identity',
    fundingStage: 'Pre-IPO',
    totalRaised: '$1.1B',
    valuation: '$7.5B',
    employees: '2000+',
    hq: 'Santa Clara, CA',
    remoteOk: true,
    careersUrl: 'https://www.netskope.com/company/careers',
    description: 'Cloud security platform. SASE and zero trust network access.',
    icpScore: 83,
    icpBreakdown: { fundingStage: 17, growthRate: 14, activelyHiring: 17, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'beyondtrust',
    name: 'BeyondTrust',
    category: 'Security & Identity',
    fundingStage: 'Private',
    employees: '1500+',
    hq: 'Johns Creek, GA',
    remoteOk: true,
    careersUrl: 'https://www.beyondtrust.com/careers',
    description: 'Privileged access management and identity security.',
    icpScore: 74,
    icpBreakdown: { fundingStage: 12, growthRate: 13, activelyHiring: 16, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 0 },
    targetRoles: ['Enterprise Account Executive'],
  },

  // GTM & REVENUE TECH
  {
    id: 'rippling',
    name: 'Rippling',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Series F+',
    totalRaised: '$1.85B',
    valuation: '$16.8B',
    arrEstimate: '$570M',
    growthRate: '30%+ YoY',
    employees: '3000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.rippling.com/careers',
    linkedinUrl: 'https://www.linkedin.com/company/rippling',
    description: 'Unified workforce management: HR, IT, and finance in one platform.',
    icpScore: 94,
    icpBreakdown: { fundingStage: 20, growthRate: 18, activelyHiring: 20, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Top priority. Aggressive hiring. Previously applied. Strong P&G/Walmart angle.',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Public',
    arrEstimate: '$2.6B+',
    growthRate: '23% YoY',
    employees: '7500+',
    hq: 'Cambridge, MA',
    remoteOk: true,
    careersUrl: 'https://www.hubspot.com/careers',
    description: 'CRM platform for marketing, sales, and service. SMB to enterprise.',
    icpScore: 80,
    icpBreakdown: { fundingStage: 13, growthRate: 13, activelyHiring: 20, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'braze',
    name: 'Braze',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Public',
    arrEstimate: '$540M+',
    growthRate: '26% YoY',
    employees: '1700+',
    hq: 'New York, NY',
    remoteOk: true,
    careersUrl: 'https://www.braze.com/company/careers',
    description: 'Customer engagement platform. Cross-channel marketing automation for enterprise.',
    icpScore: 81,
    icpBreakdown: { fundingStage: 13, growthRate: 14, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'gong',
    name: 'Gong.io',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Pre-IPO',
    totalRaised: '$584M',
    valuation: '$7.25B',
    employees: '1500+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.gong.io/careers',
    description: 'Revenue intelligence platform. AI-powered sales conversation analytics.',
    icpScore: 86,
    icpBreakdown: { fundingStage: 17, growthRate: 16, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'seismic',
    name: 'Seismic',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Pre-IPO',
    totalRaised: '$439M',
    valuation: '$3B',
    employees: '1400+',
    hq: 'San Diego, CA',
    remoteOk: true,
    careersUrl: 'https://seismic.com/careers',
    description: 'Sales enablement and revenue marketing platform. HQ in San Diego.',
    icpScore: 91,
    icpBreakdown: { fundingStage: 17, growthRate: 15, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 6 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'San Diego HQ is a major plus. Strong F1000 customer base alignment.',
  },
  {
    id: 'sprinklr',
    name: 'Sprinklr',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Public',
    arrEstimate: '$730M+',
    employees: '4000+',
    hq: 'New York, NY',
    remoteOk: true,
    careersUrl: 'https://www.sprinklr.com/careers',
    description: 'Unified customer experience management platform for the enterprise.',
    icpScore: 82,
    icpBreakdown: { fundingStage: 13, growthRate: 13, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 3 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'salesloft',
    name: 'SalesLoft',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Pre-IPO',
    totalRaised: '$245M',
    employees: '800+',
    hq: 'Atlanta, GA',
    remoteOk: true,
    careersUrl: 'https://salesloft.com/careers',
    description: 'Revenue orchestration platform. Sales engagement and pipeline management.',
    icpScore: 79,
    icpBreakdown: { fundingStage: 15, growthRate: 14, activelyHiring: 17, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 7, compSize: 1 },
    targetRoles: ['Enterprise Account Executive'],
  },
  {
    id: 'dovetail',
    name: 'Dovetail',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Series B',
    totalRaised: '$100M',
    employees: '200+',
    hq: 'Sydney, Australia',
    remoteOk: true,
    careersUrl: 'https://dovetail.com/careers',
    description: 'Customer insights platform. AI-powered research and feedback analysis.',
    icpScore: 72,
    icpBreakdown: { fundingStage: 12, growthRate: 14, activelyHiring: 14, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 6, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Mid-Market AE'],
    notes: 'Previously researched for AE role. PXM background is a strong fit.',
  },
  {
    id: 'ramp',
    name: 'Ramp',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Series D',
    totalRaised: '$1.7B',
    valuation: '$7.65B',
    employees: '800+',
    hq: 'New York, NY',
    remoteOk: true,
    careersUrl: 'https://ramp.com/careers',
    description: 'Finance automation and corporate card platform. Spend management for enterprise.',
    icpScore: 85,
    icpBreakdown: { fundingStage: 16, growthRate: 18, activelyHiring: 18, categoryMatch: 12, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },

  // WORKFLOW AUTOMATION
  {
    id: 'workato',
    name: 'Workato',
    category: 'Workflow Automation',
    fundingStage: 'Series E',
    totalRaised: '$405M',
    valuation: '$5.7B',
    employees: '1000+',
    hq: 'Mountain View, CA',
    remoteOk: true,
    careersUrl: 'https://www.workato.com/careers',
    description: 'Enterprise automation platform. Low-code integration and workflow automation.',
    icpScore: 83,
    icpBreakdown: { fundingStage: 17, growthRate: 15, activelyHiring: 17, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 1 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'Workflow Automation',
    fundingStage: 'Series F+',
    totalRaised: '$1.36B',
    valuation: '$11.7B',
    employees: '900+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://airtable.com/careers',
    description: 'Low-code app platform. Connected apps for collaborative work.',
    icpScore: 81,
    icpBreakdown: { fundingStage: 17, growthRate: 14, activelyHiring: 16, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'camunda',
    name: 'Camunda',
    category: 'Workflow Automation',
    fundingStage: 'Series C',
    totalRaised: '$92M',
    employees: '600+',
    hq: 'Berlin, Germany',
    remoteOk: true,
    careersUrl: 'https://camunda.com/careers',
    description: 'Process orchestration platform. Enterprise workflow automation at scale.',
    icpScore: 74,
    icpBreakdown: { fundingStage: 14, growthRate: 13, activelyHiring: 15, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 6, compSize: 1 },
    targetRoles: ['Enterprise Account Executive'],
  },
  {
    id: 'informatica',
    name: 'Informatica',
    category: 'Workflow Automation',
    fundingStage: 'Public',
    arrEstimate: '$1.6B+',
    employees: '5000+',
    hq: 'Redwood City, CA',
    remoteOk: true,
    careersUrl: 'https://www.informatica.com/about-us/careers.html',
    description: 'Cloud data management and integration platform. MDM, PIM, data quality.',
    icpScore: 88,
    icpBreakdown: { fundingStage: 13, growthRate: 13, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 9 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Direct overlap with PIM/MDM background. Strong F1000 install base.',
  },
  {
    id: 'sailpoint',
    name: 'SailPoint',
    category: 'Workflow Automation',
    fundingStage: 'Public',
    arrEstimate: '$600M+',
    employees: '2500+',
    hq: 'Austin, TX',
    remoteOk: true,
    careersUrl: 'https://www.sailpoint.com/careers',
    description: 'Identity security and governance platform for the enterprise.',
    icpScore: 79,
    icpBreakdown: { fundingStage: 13, growthRate: 13, activelyHiring: 18, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },

  // LOGISTICS & SUPPLY CHAIN
  {
    id: 'project44',
    name: 'project44',
    category: 'Logistics & Supply Chain',
    fundingStage: 'Series F+',
    totalRaised: '$871M',
    valuation: '$2.7B',
    employees: '900+',
    hq: 'Chicago, IL',
    remoteOk: true,
    careersUrl: 'https://www.project44.com/careers',
    description: 'Advanced visibility platform for global supply chain. Real-time freight tracking.',
    icpScore: 85,
    icpBreakdown: { fundingStage: 18, growthRate: 16, activelyHiring: 16, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Top logistics pick. F1000 shipper buyers align with your existing relationships.',
  },
  {
    id: 'fourkites',
    name: 'FourKites',
    category: 'Logistics & Supply Chain',
    fundingStage: 'Series D',
    totalRaised: '$200M+',
    employees: '600+',
    hq: 'Chicago, IL',
    remoteOk: true,
    careersUrl: 'https://www.fourkites.com/careers',
    description: 'Real-time supply chain visibility and dynamic ETA platform.',
    icpScore: 80,
    icpBreakdown: { fundingStage: 16, growthRate: 15, activelyHiring: 15, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 1 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'o9solutions',
    name: 'o9 Solutions',
    category: 'Logistics & Supply Chain',
    fundingStage: 'Series D',
    totalRaised: '$430M',
    valuation: '$2.7B',
    employees: '1000+',
    hq: 'Dallas, TX',
    remoteOk: true,
    careersUrl: 'https://o9solutions.com/careers',
    description: 'AI-powered supply chain planning platform. CPG, automotive, retail verticals.',
    icpScore: 88,
    icpBreakdown: { fundingStage: 16, growthRate: 16, activelyHiring: 16, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 10, compSize: 5 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Strong fit. Ford, GM, P&G, Walmart clients. Direct vertical overlap.',
  },
  {
    id: 'samsara',
    name: 'Samsara',
    category: 'Logistics & Supply Chain',
    fundingStage: 'Public',
    arrEstimate: '$1B+',
    growthRate: '36% YoY',
    employees: '3000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.samsara.com/company/careers',
    description: 'Connected operations platform. Fleet management, logistics, and industrial IoT.',
    icpScore: 84,
    icpBreakdown: { fundingStage: 13, growthRate: 17, activelyHiring: 20, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'relex',
    name: 'RELEX Solutions',
    category: 'Logistics & Supply Chain',
    fundingStage: 'Series D',
    totalRaised: '$500M',
    valuation: '$5B',
    employees: '2000+',
    hq: 'Helsinki, Finland',
    remoteOk: true,
    careersUrl: 'https://www.relexsolutions.com/careers',
    description: 'Supply chain and retail planning platform. Demand forecasting and replenishment.',
    icpScore: 82,
    icpBreakdown: { fundingStage: 16, growthRate: 15, activelyHiring: 16, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Strong retail/CPG vertical. Direct overlap with your P&G/Walmart relationships.',
  },
  {
    id: 'flexport',
    name: 'Flexport',
    category: 'Logistics & Supply Chain',
    fundingStage: 'Series E',
    totalRaised: '$2.3B',
    employees: '2000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.flexport.com/careers',
    description: 'Digital freight forwarding and supply chain platform.',
    icpScore: 78,
    icpBreakdown: { fundingStage: 17, growthRate: 12, activelyHiring: 15, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 8, compSize: 2 },
    targetRoles: ['Enterprise Account Executive'],
  },

  // AUTOMOTIVE SOFTWARE
  {
    id: 'tekion',
    name: 'Tekion',
    category: 'Automotive Software',
    fundingStage: 'Series D',
    totalRaised: '$550M',
    valuation: '$3.5B',
    employees: '2000+',
    hq: 'Pleasanton, CA',
    remoteOk: true,
    careersUrl: 'https://tekion.com/careers',
    description: 'Cloud-native automotive retail platform. Disrupting CDK and Reynolds & Reynolds.',
    icpScore: 87,
    icpBreakdown: { fundingStage: 16, growthRate: 17, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
    notes: 'Top automotive pick. Rippling of auto retail. Aggressive enterprise expansion.',
  },
  {
    id: 'motive',
    name: 'Motive',
    category: 'Automotive Software',
    fundingStage: 'Series E',
    totalRaised: '$400M+',
    valuation: '$2.85B',
    employees: '3000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://gomotive.com/careers',
    description: 'Fleet management and physical operations platform. AI-powered driver safety.',
    icpScore: 83,
    icpBreakdown: { fundingStage: 17, growthRate: 16, activelyHiring: 17, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 8, compSize: 1 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'cdk',
    name: 'CDK Global',
    category: 'Automotive Software',
    fundingStage: 'Private',
    employees: '8000+',
    hq: 'Hoffman Estates, IL',
    remoteOk: true,
    careersUrl: 'https://www.cdkglobal.com/careers',
    description: 'Dealer management systems and automotive retail software.',
    icpScore: 74,
    icpBreakdown: { fundingStage: 10, growthRate: 12, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 9, compSize: 0 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'fullstory',
    name: 'Fully Story',
    category: 'AI/ML Platform',
    fundingStage: 'Series E',
    totalRaised: '$357M',
    employees: '500+',
    hq: 'Atlanta, GA',
    remoteOk: true,
    careersUrl: 'https://www.fullstory.com/careers',
    description: 'Digital experience intelligence platform. Behavioral data analytics.',
    icpScore: 78,
    icpBreakdown: { fundingStage: 17, growthRate: 14, activelyHiring: 14, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 8, compSize: 1 },
    targetRoles: ['Enterprise Account Executive', 'Mid-Market AE'],
  },
  {
    id: 'kong',
    name: 'Kong',
    category: 'Data Infrastructure',
    fundingStage: 'Series E',
    totalRaised: '$171M',
    employees: '500+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://konghq.com/careers',
    description: 'API connectivity platform. Cloud-native API gateway and service mesh.',
    icpScore: 76,
    icpBreakdown: { fundingStage: 17, growthRate: 13, activelyHiring: 14, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 6, compSize: 1 },
    targetRoles: ['Enterprise Account Executive'],
  },
  {
    id: 'miro',
    name: 'Miro',
    category: 'Workflow Automation',
    fundingStage: 'Series C',
    totalRaised: '$476M',
    valuation: '$17.5B',
    employees: '1800+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://miro.com/careers',
    description: 'Visual collaboration platform. Innovation workspace for enterprise teams.',
    icpScore: 80,
    icpBreakdown: { fundingStage: 14, growthRate: 14, activelyHiring: 18, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'Workflow Automation',
    fundingStage: 'Pre-IPO',
    totalRaised: '$333M',
    valuation: '$12.5B',
    employees: '1400+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.figma.com/careers',
    description: 'Collaborative design and prototyping platform. Now expanding into enterprise.',
    icpScore: 82,
    icpBreakdown: { fundingStage: 17, growthRate: 15, activelyHiring: 17, categoryMatch: 12, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'block',
    name: 'Block',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Public',
    employees: '12000+',
    hq: 'Oakland, CA',
    remoteOk: true,
    careersUrl: 'https://block.xyz/careers',
    description: 'Financial services and commerce ecosystem. Square, Cash App, and Spiral.',
    icpScore: 75,
    icpBreakdown: { fundingStage: 12, growthRate: 12, activelyHiring: 18, categoryMatch: 12, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive'],
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Data Infrastructure',
    fundingStage: 'Public',
    employees: '3000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://github.com/about/careers',
    description: 'AI-powered developer platform. Copilot and enterprise DevSecOps.',
    icpScore: 80,
    icpBreakdown: { fundingStage: 13, growthRate: 14, activelyHiring: 18, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 9, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Private',
    arrEstimate: '$1.9B+',
    employees: '6000+',
    hq: 'San Francisco, CA',
    remoteOk: true,
    careersUrl: 'https://www.zendesk.com/jobs',
    description: 'Customer service platform. AI-powered support and CX for enterprise.',
    icpScore: 78,
    icpBreakdown: { fundingStage: 12, growthRate: 12, activelyHiring: 18, categoryMatch: 14, remoteOk: 10, fortune1000Buyers: 10, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
  {
    id: 'prosper-ops',
    name: 'Prosper Ops',
    category: 'GTM & Revenue Tech',
    fundingStage: 'Series A',
    employees: '50+',
    hq: 'Austin, TX',
    remoteOk: true,
    careersUrl: 'https://prosperops.com/careers',
    description: 'Autonomous cloud cost optimization platform.',
    icpScore: 65,
    icpBreakdown: { fundingStage: 8, growthRate: 13, activelyHiring: 13, categoryMatch: 13, remoteOk: 10, fortune1000Buyers: 6, compSize: 2 },
    targetRoles: ['Enterprise Account Executive', 'Mid-Market AE'],
  },
  {
    id: 'nvidia',
    name: 'Nvidia',
    category: 'AI/ML Platform',
    fundingStage: 'Public',
    employees: '30000+',
    hq: 'Santa Clara, CA',
    remoteOk: true,
    careersUrl: 'https://www.nvidia.com/en-us/about-nvidia/careers',
    description: 'AI computing platform. GPU infrastructure and enterprise AI software.',
    icpScore: 76,
    icpBreakdown: { fundingStage: 12, growthRate: 16, activelyHiring: 18, categoryMatch: 15, remoteOk: 10, fortune1000Buyers: 5, compSize: 0 },
    targetRoles: ['Enterprise Account Executive', 'Strategic Account Executive'],
  },
]

export function getCompaniesByCategory(category: CompanyCategory): Company[] {
  return TARGET_COMPANIES.filter(c => c.category === category)
}

export function getTopCompanies(limit = 10): Company[] {
  return [...TARGET_COMPANIES].sort((a, b) => b.icpScore - a.icpScore).slice(0, limit)
}

export function searchCompanies(query: string): Company[] {
  const q = query.toLowerCase()
  return TARGET_COMPANIES.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.category.toLowerCase().includes(q) ||
    c.description.toLowerCase().includes(q) ||
    c.targetRoles.some(r => r.toLowerCase().includes(q))
  )
}
